# Generated by Django 2.0.2 on 2019-05-02 20:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0002_letter_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='letter_html',
            field=models.CharField(default=django.utils.timezone.now, max_length=20000),
            preserve_default=False,
        ),
    ]
