# Generated by Django 2.0.2 on 2019-05-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0003_letter_letter_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='letter_html',
            field=models.CharField(blank=True, max_length=20000),
        ),
    ]
