# Generated by Django 2.0.2 on 2019-05-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0004_auto_20190502_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=20000)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('hasChecked', models.BooleanField()),
                ('check_date', models.DateTimeField(verbose_name='date checked')),
            ],
        ),
    ]
