# Generated by Django 2.0.2 on 2019-05-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0005_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='check_date',
            field=models.DateTimeField(blank=True, verbose_name='date checked'),
        ),
    ]
