# Generated by Django 2.0.2 on 2019-05-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0008_chatbot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbot',
            name='maintenance_mode',
        ),
        migrations.AddField(
            model_name='todo',
            name='todo',
            field=models.CharField(blank=True, max_length=20000),
        ),
        migrations.AddField(
            model_name='todo',
            name='todo_md',
            field=models.CharField(blank=True, max_length=20000),
        ),
    ]
