# Generated by Django 2.0.2 on 2019-05-07 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0009_auto_20190507_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='todo',
            new_name='plan_html',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='todo_md',
            new_name='plan_md',
        ),
    ]
