# Generated by Django 2.0.2 on 2019-05-07 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0010_auto_20190507_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='letter_html',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='plan_html',
        ),
    ]
